/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.*;

import java.util.ArrayList;
import DTO.*;
import BUS.*;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import com.toedter.calendar.JDateChooser;

import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.AncestorListener;
import javax.swing.event.AncestorEvent;
import javax.swing.JButton;

/**
 *
 * @author macar
 */
public class ThongKeGUI extends javax.swing.JPanel {
    
    String[] header = new String[]{"Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lần Nhập", "Số Lần Bán", "Tổng Nhập", "Tổng Bán", "Lợi Nhuận"};
    DefaultTableModel model = new DefaultTableModel(header,0);
    private ThongKeBUS tksp = new ThongKeBUS();
    
    String[] header2 = new String[]{"Mã Nhân Viên", "Tên Nhân Viên", "SL Đơn Nhập", "SL Đơn Bán", "Tổng Bán"};
    DefaultTableModel model2 = new DefaultTableModel(header2,0);
    private ThongKeBUS tknv = new ThongKeBUS();
    
    String[] header3 = new String[]{"Mã Khách Hàng", "Tên Khách Hàng", "Số Lần Mua", "Tổng Điểm TL", "Tổng Mua"};
    DefaultTableModel model3 = new DefaultTableModel(header3,0);
    private ThongKeBUS tkkh = new ThongKeBUS();
    
    ArrayList<HoaDonDTO> hdlist;
    HoaDonBUS hdbus = new HoaDonBUS();
    ArrayList<TKSanPham> tk1;
    ArrayList<TKNhanVien> tk2;
    ArrayList<TKKhachHang> tk3;
    JDateChooser datef,datet;
    ThongKeBUS tkbus = new ThongKeBUS();

    /**
     * Creates new form ThongKeGUI
     */
    public ThongKeGUI() {
        initComponents();
        if(hdbus.getList()==null)hdbus.list();
        hdlist=hdbus.getList();
        list_tksp(hdlist);
        list_tknv(hdlist);
        list_tkkh(hdlist);
    }
    
    //----------Thống kê sản phẩm----------
    public void list_tksp(ArrayList<HoaDonDTO> hd) {
        tksp.list(hd);
        tk1 = tksp.getListsp();
        model.setRowCount(0);
        loadTKSP(tk1);
    }
    public void loadTKSP(ArrayList<TKSanPham> tksp){
        Vector data;
        model.setRowCount(0);
        for(TKSanPham tk1 : tksp){
            data=new Vector();
            data.add(tk1.getMaSP());
            data.add(tk1.getTenSP());
            data.add(tk1.getSlNhap());
            data.add(tk1.getSlBan());
            data.add(tk1.getTongNhap());
            data.add(tk1.getTongBan());
            data.add(tk1.getLoinhuan());
            model.addRow(data);
        }
        tbTKSP.setModel(model);
    }

//---------Thống Kê Nhân Viên---------
    public void list_tknv(ArrayList<HoaDonDTO> hd) {
        tknv.listnv(hd);
        tk2 = tknv.getListnv();
        model2.setRowCount(0);
        loadTKNV(tk2);
    }
    public void loadTKNV(ArrayList<TKNhanVien> tknv){
        Vector data;
        model2.setRowCount(0);
        for(TKNhanVien tk2 : tknv){
            data=new Vector();
            data.add(tk2.getMaNV());
            data.add(tk2.getTenNV());
            data.add(tk2.getSlpn());
            data.add(tk2.getSlhd());
            data.add(tk2.getTongban());
            model2.addRow(data);
        }
        tbTKNV.setModel(model2);
    }
    
//----------Thống Kê Khách Hàng----------
    public void list_tkkh(ArrayList<HoaDonDTO> hd) {
        tkkh.listkh(hd);
        tk3 = tkkh.getListkh();
        model3.setRowCount(0);
        loadTKKH(tk3);
    }
    public void loadTKKH(ArrayList<TKKhachHang> tkkh){
        Vector data;
        model3.setRowCount(0);
        for(TKKhachHang tk3 : tkkh){
            data=new Vector();
            data.add(tk3.getMaKH());
            data.add(tk3.getTenKH());
            data.add(tk3.getSlmua());
            data.add(tk3.getDiemtl());
            data.add(tk3.getTongMua());
            model3.addRow(data);
        }
        tbTKKH.setModel(model3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public ArrayList<HoaDonDTO> taohoadontheoquy(int c) {
    	int start=0,end=0;
    	ArrayList<HoaDonDTO> hdc = new ArrayList();
    	switch(c){
    		case 1:{
    			start=1;
    			end=3;
    			break;
    		}
    		case 2:{
    			start=4;
    			end=6;
    			break;
    		}
    		case 3:{
    			start=7;
    			end=9;
    			break;
    		}
    		case 4:{
    			start=10;
    			end=12;
    			break;
    		}
    		default:break;
    	}
    	for(HoaDonDTO s: hdlist) {
    		String date = s.getNgayLap();
    		String[] split = new String[3];
    		split=date.split("-");
    		if(Integer.parseInt (split[1]) >= start && Integer.parseInt (split[1]) <= end) {
    			hdc.add(s);
    		}
    	}
    	return hdc;
    }
    public ArrayList<HoaDonDTO> taohoadontheonam(int c) {
    	int year=0;
    	ArrayList<HoaDonDTO> hdc = new ArrayList();
    	switch(c){
    		case 1:{
    			year=2019;
    			break;
    		}
    		case 2:{
    			year=2020;
    			break;
    		}
    		case 3:{
    			year=2021;
    			break;
    		}
    		default:break;
    	}
    	for(HoaDonDTO s: hdlist) {
    		String date = s.getNgayLap();
    		String[] split = new String[3];
    		split=date.split("-");
    		if(Integer.parseInt (split[0]) ==year) {
    			hdc.add(s);
    		}
    	}
    	return hdc;
    }
    public ArrayList<HoaDonDTO> taohoadontheolich(){
    	return hdbus.ListTime(datef.getDate(),datet.getDate());
    }
    public void loadhoadontheolich() {
    ArrayList<HoaDonDTO> hd = new ArrayList();
	hd=taohoadontheolich();
	if(!hd.isEmpty()) {
		list_tksp(hd);
        list_tknv(hd);
        list_tkkh(hd);
        
    }
	else {
		JOptionPane.showMessageDialog(null, "không có hóa đơn nào được thanh toán trong khoảng thời gian này ");
		list_tksp(hdlist);
        list_tknv(hdlist);
        list_tkkh(hdlist);
        
       
	}
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	this.setBounds(0, 0,1500,600);
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTKSP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTKNV = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTKKH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        
        tbTKSP.setDefaultEditor(Object.class, null);
        tbTKKH.setDefaultEditor(Object.class, null);
        tbTKNV.setDefaultEditor(Object.class, null);
        
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		list_tksp(hdlist);
                list_tknv(hdlist);
                list_tkkh(hdlist);
                jComboBox2.setSelectedIndex(0);
                jComboBox3.setSelectedIndex(0);
                datef.setDate(null);
                datet.setDate(null);
        	}
        });
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		jComboBox3.setEnabled(false);
            	jComboBox2.setEnabled(false);
            	jComboBox2.setSelectedIndex(0);
            	jComboBox3.setSelectedIndex(0);
        	}
        });
        jComboBox2 = new javax.swing.JComboBox<>();
        datef = new JDateChooser();
        datet = new JDateChooser();
        datef.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {

			@Override
			public void propertyChange(PropertyChangeEvent evt) {
				// TODO Auto-generated method stub
				datet.setMinSelectableDate(datef.getDate());
			}
        });
        
        datet.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
        	
			@Override
			public void propertyChange(PropertyChangeEvent evt) {
				// TODO Auto-generated method stub
				datef.setMaxSelectableDate(datet.getDate());
			}
        });
        jComboBox2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        			int c= jComboBox2.getSelectedIndex();
        			if(c>0) {
        			if(!taohoadontheoquy(c).isEmpty()) {
        		    list_tksp(taohoadontheoquy(c));
        	        list_tknv(taohoadontheoquy(c));
        	        list_tkkh(taohoadontheoquy(c));
        			}
        			else {
        				JOptionPane.showMessageDialog(null, "không có hóa đơn nào được thanh toán vào quý "+c);
        				list_tksp(hdlist);
            	        list_tknv(hdlist);
            	        list_tkkh(hdlist);
            	        jComboBox2.setSelectedIndex(0);
        			}
        			}
        			else {
        				list_tksp(hdlist);
            	        list_tknv(hdlist);
            	        list_tkkh(hdlist);
        			}
        	}
        });
        jComboBox2.setEnabled(false);
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int c= jComboBox3.getSelectedIndex();
    			if(c>0) {
    			if(!taohoadontheonam(c).isEmpty()) {
    		    list_tksp(taohoadontheonam(c));
    	        list_tknv(taohoadontheonam(c));
    	        list_tkkh(taohoadontheonam(c));
    			}
    			else {
    				JOptionPane.showMessageDialog(null, "không có hóa đơn nào được thanh toán vào năm "+jComboBox3.getSelectedItem());
    				list_tksp(hdlist);
        	        list_tknv(hdlist);
        	        list_tkkh(hdlist);
        	        jComboBox3.setSelectedIndex(0);
    			}
    			}
    			else {
    				list_tksp(hdlist);
        	        list_tknv(hdlist);
        	        list_tkkh(hdlist);
    			}
    	}
        });
        jComboBox3.setEnabled(false);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbTKSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng nhập", "Số lượng bán", "Tổng Nhập", "Tổng Bán", "Lợi Nhuận"
            }
        ));
        jScrollPane1.setViewportView(tbTKSP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel1);

        tbTKNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Số hóa đơn bán", "Số đơn hàng nhập", "Tổng Bán"
            }
        ));
        jScrollPane2.setViewportView(tbTKNV);

        jLabel4.setText("Từ ngày");

        jLabel5.setText("Đến ngày");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jLabel4)
                    .addGap(28, 28, 28)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(48, 48, 48)
                    .addComponent(jLabel5)
                    .addContainerGap(305, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(196, 196, 196)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addContainerGap(124, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Nhân Viên", jPanel2);

        tbTKKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Số lần mua hàng", "Tổng điểm tích lũy", "Tổng tiền mua"
            }
        ));
        jScrollPane3.setViewportView(tbTKKH);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Khách Hàng", jPanel3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("THỐNG KÊ DOANH SỐ SIÊU THỊ");

        jButton1.setText("Xác Nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Theo Năm");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Theo Qúy");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Theo lịch\r\n");


        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Tất cả","Quý 1", "Quý 2", "Quý 3", "Quý 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Tất cả","Năm 2019", "Năm 2020", "Năm 2021", " " }));
        
        JButton export = new JButton();
        export.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int c=jTabbedPane1.getSelectedIndex();
        		switch(c) {
        		case 0:{
        			tkbus.ExportExcelSP();
        			break;
        		}
        		case 1:{
        			tkbus.ExportExcelNV();
        			break;
        		}
        		case 2:{
        			tkbus.ExportExcelKH();
        			break;
        		}
        		default:{
        			JOptionPane.showMessageDialog(null, "Export không thành công "+c);
        		}
        		}
        	}
        });
        export.setText("Export");
        GroupLayout groupLayout = new GroupLayout(this);
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(206)
        			.addComponent(jLabel1))
        		.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 1500, GroupLayout.PREFERRED_SIZE)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(99)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(datef, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
        					.addGap(42)
        					.addComponent(datet, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(jRadioButton1)
        					.addGap(56)
        					.addComponent(jRadioButton2)
        					.addGap(81)
        					.addComponent(jRadioButton3)
        					.addGap(104)
        					.addComponent(jButton1)
        					.addGap(18)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(export, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
        					.addGap(31)
        					.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE))))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(26)
        			.addComponent(jLabel1)
        			.addGap(26)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jRadioButton1)
        				.addComponent(jRadioButton2)
        				.addComponent(jRadioButton3)
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jButton1)
        					.addComponent(jButton2)
        					.addComponent(export)))
        			.addGap(30)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(34)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(datet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(datef, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(61)
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 360, GroupLayout.PREFERRED_SIZE))
        );
        setLayout(groupLayout);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	if(datef.getDate()!=null && datet.getDate()!=null) {
			loadhoadontheolich();
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    	jComboBox3.setEnabled(true);
    	jComboBox2.setEnabled(false);
    	jComboBox2.setSelectedIndex(0);
    	datef.setDate(null);
        datet.setDate(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    	jComboBox2.setEnabled(true);
    	jComboBox3.setEnabled(false);
    	jComboBox3.setSelectedIndex(0);
    	datef.setDate(null);
        datet.setDate(null);
    	// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tbTKKH;
    private javax.swing.JTable tbTKNV;
    private javax.swing.JTable tbTKSP;
}
